spring.application.name=To-Do-List
spring.datasource.url=jdbc:postgresql://localhost:5432/todolistdatabase
spring.datasource.username=postgres
spring.datasource.password=#DBConnection#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


